### ISSUE TITLE
想问一下能否适配hsuyelin/nas-tools

### ISSUE THREAD

**Issue by sakurasep** [Mattoids/nas-tools-plugin#2]
docker版目前使用的这个nastool维护安装时会显示
套件版本不要符合安装要求，不支持安装！
希望能适配一下，感谢

**Comment by Mattoids** [comment]
该项目由 @hsuyelin 在维护，这里不会对该项目进行支持的。
主要因为这个适配是侵入式的，作者一单更新了程序，那么就意味着适配包可能失效。而且这个作者的更新也很频繁的，完全不需要第三方商店里面的插件。最核心的几个插件作者也已经集成进去了

**Comment by sakurasep** [comment]
> 该项目由 @hsuyelin 在维护，这里不会对该项目进行支持的。 主要因为这个适配是侵入式的，作者一单更新了程序，那么就意味着适配包可能失效。而且这个作者的更新也很频繁的，完全不需要第三方商店里面的插件。最核心的几个插件作者也已经集成进去了

好的，感谢回复
