### ISSUE TITLE
大佬 3.3.1能用嘛

### ISSUE THREAD

**Issue by zazjaya** [Mattoids/nas-tools-plugin#4]
大佬 3.3.1能用嘛

**Comment by Mattoids** [comment]
这个不能，3.3.1是别的作者维护的，他没有引入三方插件的功能，所以就无法使用

**Comment by Mattoids** [comment]
不过你可以尝试将插件放在 `config/plugins` 目录下，这是原作者做的三方插件入口。但第三方库部分插件是依赖nastool的系统逻辑的，这些逻辑我可能做了修改，所以依赖这部分逻辑的插件就无法使用。例如`自定义索引器`

**Comment by zazjaya** [comment]
好的谢谢您
